apiVersion: v1
kind: Service
metadata:
  name: ca-ccca5
  namespace: biodiversity
  labels:
    app: ca-ccca5
spec:
  type: ClusterIP
  selector:
    app: ca-ccca5
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
      name: http
